# Generated by Django 5.2.4 on 2025-08-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('mentor', 'Mentor'), ('mentee', 'Mentee'), ('saver', 'Savings Group Member')], default='buyer', max_length=20),
        ),
    ]
