# Generated by Django 5.2.4 on 2025-08-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='group',
        ),
        migrations.RemoveField(
            model_name='savingsmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='savingsmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavingsGroup',
        ),
        migrations.DeleteModel(
            name='SavingsMember',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
